fix: spark dataframe saveAsTable fails (#173)
Spark Dataframe saveAsTable fails due to missing NoSuchTableException.
We met below error when upgrade lance projects version.

```java
py4j.protocol.Py4JJavaError: An error occurred while calling o140.saveAsTable.
: TableNotFoundException{code=4, message='Table does not exist: lance_test_database.blobtable2', detail='TableNotFound', instance='lance_test_database.blobtable2'}
	at org.lance.namespace.hive2.Hive2Namespace.describeTable(Hive2Namespace.java:286)
	at org.lance.OpenDatasetBuilder.buildFromNamespace(OpenDatasetBuilder.java:200)
	at org.lance.OpenDatasetBuilder.build(OpenDatasetBuilder.java:186)
	at org.lance.spark.BaseLanceNamespaceSparkCatalog.loadTable(BaseLanceNamespaceSparkCatalog.java:373)
	at org.apache.spark.sql.connector.catalog.TableCatalog.loadTable(TableCatalog.java:130)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:592)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

The root cause is as below:

<img width="1244" height="500" alt="image"
src="https://github.com/user-attachments/assets/0d6efcda-9178-4d24-9078-a646afff4f1e"
/>

---------

Co-authored-by: zhanghaobo@kanzhun.com <zhanghaobo@kanzhun.com>